# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'permissions': (('read_item', 'Can read item'),), 'verbose_name': 'Cat', 'verbose_name_plural': 'Cats'},
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='cat_owner',
            new_name='animal_owner',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='dog_owner',
            new_name='animal_owner',
        ),
    ]
